### PR TITLE
Modifies the behavior of using space as the first candidate key

### PR DESCRIPTION
**Pull request by zonble**
Currently we just simply insert the space key to the beginning of the candidate list. However, the users expect that they can use both space and the original first key to select the first candidate. This is for #30.

### CODE REVIEW

**Comment by lukhnos** [comment]
Based on the code, this will change the current behavior of displaying 10 candidates (Space + 123456789) to displaying 9 candidates (Space + 23456789) with "1" still being allowed to select the first candidate, right?

I'm concerned with whether this affects enough people who expect Space chooses the first candidate, 1 chooses the second (and so on). I recall this has been the behavior since long time ago. If we want to address #30, could this be made into an advanced option?

**Comment by zonble** [comment]
> Based on the code, this will change the current behavior of displaying 10 candidates (Space + 123456789) to displaying 9 candidates (Space + 23456789) with "1" still being allowed to select the first candidate, right?

Yes.

> I'm concerned with whether this affects enough people who expect Space chooses the first candidate, 1 chooses the second (and so on). I recall this has been the behavior since long time ago. If we want to address #30, could this be made into an advanced option?

I guess we can have another choice. We can make the setting from a checkbox to a option list

```
Use space as the first candidate key

1. Disabled.
2. Enabled, and the original first key to select the second candidate.
3. Enabled, and both space and the original first key to select the first candidate.
```

How about that?

**Comment by lukhnos** [comment]
> I guess we can have another choice. We can make the setting from a checkbox to a option list

SGTM.

**Comment by zonble** [comment]
I updated the code. Please review. Thanks!

**Review by lukhnos — APPROVED** [review]

**Pull request merged**
